# Site settings
author: Cole Rau
title: Flatiron Student Blog
header-img: img/home-bg.png
email: colevrau@gmail.com
copyright_name: Cole Rau
description: > # this means to ignore newlines until "baseurl:"
  Cole Rau
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  colerau

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
